# .github/workflows/ghidra-ci.yml
name: Build Ghidra Plugin

on:
  push:
    branches: ["main"]
    paths:
      - 'extensions/**'
      - '.github/workflows/ghidra-ci.yml'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ["17", "21"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Install Gradle (cache disabled)
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Build Ghidra plugin
        run: |
          cd ghidra
          gradle -I gradle/support/fetchDependencies.gradle
          gradle buildGhidra

      - name: Rename and package plugin
        run: |
          mkdir -p plugin-dist
          for file in ghidra/build/dist/*.zip; do
            base=$(basename "$file")
            version_tag=$(git describe --tags --abbrev=0 || echo latest)
            cp "$file" "plugin-dist/lucid-extension-${version_tag}.zip"
          done

      - name: Upload plugin as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lucid-ghidra-plugin
          path: plugin-dist/*.zip

  release-assets:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: lucid-ghidra-plugin

      - name: Generate release notes from changelog
        id: changelog
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "Extracting notes for $TAG_NAME"
          awk "/## \[${TAG_NAME#v}\]/,/^## \[/" CHANGELOG.md | head -n -1 > release_notes.md
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          cat release_notes.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload ZIP and notes to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: lucid-ghidra-plugin/*.zip
          body: ${{ env.RELEASE_NOTES }}
